### ISSUE TITLE
Add Hamburger to boilerplate?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#42] opened 2017-12-06 23:40 UTC
This is basically a perfect hamburger menu that we use on almost all sites.

```
<template>
    <div class="hamburger" v-on:click="toggleMenu">
        <div class="line line-1"></div>
        <div class="line line-2"></div>
        <div class="line line-3"></div>
    </div>
</template>

<script>
    export default {
        methods: {
            toggleMenu(e) {
                if(this.$store.state.menuOpened) {
                    this.$store.commit('CLOSE_MENU')
                } else {
                    this.$store.commit('OPEN_MENU')
                }
            }
        }
    }
</script>

<style lang="scss">
    //@import 'src/styles/vars';

    .hamburger {
        border-radius: 100%;
        position: fixed;
        cursor: pointer;
        height: 18px;
        width: 30px;
        left: 10px;
        top: 10px;
        padding: 20px;

        .line {
            transition: all 0.3s;
            transform-origin: center;
            background-color: $black;
            position: absolute;
            height: 2px;
            width: 30px;
            left: 20px;
            top: 20px;
        }
        .line-2 {
            top: 28px;
        }
        .line-3 {
            top: 36px;
        }

    }

    /* Menu opened*/
    .menu-opened .hamburger {
        .line {
            background-color: $red;
        }
        .line-1 {
            top: 25px;
            transform: rotate(-45deg);
        }
        .line-2,
        .line-3 {
            top: 25px;
            transform: rotate(45deg);
        }
    }
</style>
```

**Comment by SaFrMo** [comment] 2017-12-08 15:41
@jrobson153 and I were talking about making the hamburger an SVG on future sites - that could add some more flexibility in styling, sizing, and animation. Any thoughts on that @drewbaker ?

**Comment by SaFrMo** [comment] 2017-12-14 21:35
Something like [this](https://codepen.io/SanderMoolin/pen/rpVpqg) is pretty reusable, and would give us a lot more specific control over animations.

**Comment by SaFrMo** [comment] 2017-12-15 14:56
Closing as a duplicate of #46

**Closed by SaFrMo** 2017-12-15 14:56 UTC
